# Generated by Django 2.0 on 2018-01-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_migrate_translatable_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
