# Generated by Django 2.0 on 2017-12-19 17:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='last_accessed',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 17, 24, 45, 701256, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
